import {$,number,money,metric,numberField,selectField,readFields,formShell} from "./utils.js";
import {precipitationCalculator} from "./chemistry.js";
import {dewateringCalculators} from "./dewatering.js";
import {influentDosingCalculator} from "./influent-dosing-calculator.js";

const simple=(config)=>({...config,render(workspace){workspace.innerHTML=formShell({category:config.category,title:config.name,formula:config.formula,description:config.short,fields:config.fields});$("#resetForm").onclick=()=>config.render?config.render(workspace):this.render(workspace);$("#calculatorForm").onsubmit=e=>{e.preventDefault();const v=readFields(config.fields);if(!v)return;const value=config.calculate(v);$("#result").innerHTML=`<section class="result-hero"><small>Ergebnis</small><strong>${config.unit==="€"?money(value):number(value,config.digits??3)+" "+config.unit}</strong></section>${config.extra?config.extra(v,value):""}`;};}});

const basics=[
 simple({id:"load",category:"Grundlagen",name:"Tagesfracht",short:"Volumenstrom und Konzentration in eine Tagesfracht umrechnen.",formula:"B = Q × c ÷ 1.000",fields:[numberField("q","Volumenstrom","m³/d"),numberField("c","Konzentration","mg/l")],calculate:v=>v.q*v.c/1000,unit:"kg/d",digits:4}),
 simple({id:"concentration",category:"Grundlagen",name:"Konzentration",short:"Konzentration aus Fracht und Volumenstrom bestimmen.",formula:"c = B × 1.000 ÷ Q",fields:[numberField("b","Tagesfracht","kg/d"),numberField("q","Volumenstrom","m³/d",.000001)],calculate:v=>v.b*1000/v.q,unit:"mg/l",digits:3}),
 simple({id:"loading",category:"Biologie",name:"Schlammbelastung",short:"BSB₅-Fracht bezogen auf das TS-Inventar.",formula:"BTS = BSB₅ ÷ (V × TS)",fields:[numberField("b","BSB₅-Fracht","kg/d"),numberField("v","Belebungsvolumen","m³",.000001),numberField("ts","TS","kg/m³",.000001)],calculate:v=>v.b/(v.v*v.ts),unit:"kg BSB₅/(kg TS·d)",digits:4}),
 simple({id:"sludge-age",category:"Biologie",name:"Schlammalter",short:"TS-Inventar bezogen auf den täglichen Feststoffabzug.",formula:"tTS = TS-Inventar ÷ Feststoffabzug",fields:[numberField("inventory","TS-Inventar","kg"),numberField("withdrawal","Feststoffabzug","kg TS/d",.000001)],calculate:v=>v.inventory/v.withdrawal,unit:"d",digits:2}),
 simple({id:"svi",category:"Schlamm",name:"SVI",short:"Schlammvolumenindex aus SV₃₀ und TS.",formula:"SVI = SV₃₀ ÷ TS",fields:[numberField("sv","SV₃₀","ml/l"),numberField("ts","TS","g/l",.000001)],calculate:v=>v.sv/v.ts,unit:"ml/g",digits:1}),
 simple({id:"hrt",category:"Hydraulik",name:"Aufenthaltszeit",short:"Hydraulische Aufenthaltszeit aus Volumen und Tagesdurchfluss.",formula:"t = V ÷ Q × 24",fields:[numberField("v","Beckenvolumen","m³"),numberField("q","Volumenstrom","m³/d",.000001)],calculate:v=>v.v/v.q*24,unit:"h",digits:2}),
 simple({id:"dose",category:"Chemikalien",name:"Dosierstrom",short:"Dosierstrom aus Wasserstrom und spezifischer Dosierung.",formula:"V̇ = Q × D ÷ 1.000",fields:[numberField("q","Wasserstrom","m³/h"),numberField("d","Dosierung","ml/m³")],calculate:v=>v.q*v.d/1000,unit:"l/h",digits:3}),
 simple({id:"tank",category:"Chemikalien",name:"Tankreichweite",short:"Reichweite eines Chemikalienbestandes.",formula:"t = Bestand ÷ Tagesverbrauch",fields:[numberField("stock","Tankinhalt","l"),numberField("use","Verbrauch","l/d",.000001)],calculate:v=>v.stock/v.use,unit:"d",digits:1}),
 simple({id:"cost",category:"Wirtschaftlichkeit",name:"Chemikalienkosten",short:"Verbrauch und Preis auf einen Zeitraum hochrechnen.",formula:"K = Verbrauch × Preis × Zeitraum",fields:[numberField("use","Verbrauch","kg/d"),numberField("price","Preis","€/kg"),selectField("period","Zeitraum",["Tag","30 Tage","365 Tage"])],calculate:v=>v.use*v.price*(v.period==="Tag"?1:v.period==="30 Tage"?30:365),unit:"€",digits:2})
];
export const calculators=[precipitationCalculator,influentDosingCalculator,...dewateringCalculators,...basics];
