import {$,number,money,metric,hint,numberField,selectField,fieldHtml,readFields,formShell} from "./utils.js";

const TECHNIQUES={
  "Dekanterzentrifuge":{liquid:"Zentrat",note:"Kontinuierliche mechanische Entwässerung. Drehmoment, Differenzdrehzahl, Teichtiefe und Polymer sind wichtige Stellgrößen."},
  "Bandfilterpresse":{liquid:"Filtrat",note:"Kontinuierliche Entwässerung mit Schwerkraft- und Presszone. Bandbelastung, Spülung und Flockenstabilität beachten."},
  "Schneckenpresse":{liquid:"Filtrat",note:"Langsam laufende Entwässerung. Zulaufkonditionierung, Ringspalt und Pressdruck sind relevante Betriebsgrößen."},
  "Kammerfilterpresse":{liquid:"Filtrat",note:"Diskontinuierliche Druckfiltration. Zykluszeit, Füllgrad und Austragsverhalten berücksichtigen."},
  "Siebband / Eindicker":{liquid:"Filtrat",note:"Primär für Eindickung. Ergebnis-TS und Feststoffrückhalt sind getrennt von einer Hochleistungsentwässerung zu bewerten."},
  "Benutzerdefiniert":{liquid:"Flüssigphase",note:"Freie Technik. Bezeichnungen und typische Betriebsbereiche anlagenspezifisch interpretieren."}
};
const techField=()=>selectField("technique","Entwässerungstechnik",Object.keys(TECHNIQUES));
const calculator=(id,name,short,formula,render)=>({id,category:"Schlammentwässerung",name,short,formula,render});

export const dewateringCalculators=[
calculator("dw-throughput","TS-Durchsatz","Hydraulischer Schlammstrom und TS-Gehalt","mTS = Q × TS",renderThroughput),
calculator("dw-cake","Schlammkuchenmenge","Kuchenmenge aus TS-Fracht, Rückhalt und Kuchen-TS","mKuchen = mTS × η ÷ TS_Kuchen",renderCake),
calculator("dw-retention","Feststoffrückhalt","Frachtbasierter Feststoffrückhalt über Zulauf und Flüssigphase","η = (Bzu − Bab) ÷ Bzu × 100",renderRetention),
calculator("dw-polymer","Polymerbedarf","Wirksubstanz, Handelsprodukt, Dosierstrom und Kosten","Polymer = TS × kg WS/t TS",renderPolymer),
calculator("dw-disposal","Entsorgungskosten","Kosten der Schlammkuchenentsorgung","K = Kuchenmenge × Preis",renderDisposal),
calculator("dw-compare","Vorher-Nachher-Vergleich","Kuchen-TS, Polymer und Entsorgung wirtschaftlich vergleichen","Netto = Entsorgung + Polymer vorher − nachher",renderCompare)
];

function techniqueInfo(){const name=$("#field-technique").value,t=TECHNIQUES[name];$("#techInfo").innerHTML=`<strong>${name}</strong><br>${t.note}<br>Bezeichnung der Flüssigphase: <strong>${t.liquid}</strong>.`;}
function bind(workspace,fields,calculate){$("#field-technique")?.addEventListener("change",techniqueInfo);if($("#techInfo"))techniqueInfo();$("#resetForm").onclick=()=>workspace._rerender();$("#calculatorForm").onsubmit=e=>{e.preventDefault();const v=readFields(fields);if(v)calculate(v,$("#result"));};}
function setup(workspace,html,rerender){workspace.innerHTML=html;workspace._rerender=rerender;}

function renderThroughput(workspace){
  const fields=[techField(),numberField("flow","Schlammvolumenstrom","m³/h",0),numberField("ts","TS-Gehalt","kg/m³",0),numberField("hours","Betriebszeit","h/d",0.000001,24,8),numberField("days","Betriebstage","d/a",0,366,250)];
  setup(workspace,formShell({category:"Schlammentwässerung",title:"TS-Durchsatz",formula:"mTS = Q × TS",description:"Berechnet den hydraulischen und trockensubstanzbezogenen Durchsatz der ausgewählten Entwässerungstechnik.",fields,info:'<div id="techInfo"></div>'}),()=>renderThroughput(workspace));
  bind(workspace,fields,(v,out)=>{const kgH=v.flow*v.ts,kgD=kgH*v.hours,tA=kgD*v.days/1000;out.innerHTML=`<span class="tech-badge">${v.technique}</span><section class="result-hero"><small>TS-Durchsatz</small><strong>${number(kgH,2)} kg TS/h</strong><p>${number(kgD,2)} kg TS/d bei ${number(v.hours,1)} Betriebsstunden</p></section><div class="metrics">${metric("Hydraulischer Durchsatz",number(v.flow,3)+" m³/h")}${metric("TS-Gehalt",number(v.ts,3)+" kg/m³")}${metric("TS pro Tag",number(kgD,2)+" kg/d")}${metric("TS pro Jahr",number(tA,2)+" t/a")}</div>${hint("Bewertung","TS-Durchsatz und hydraulischer Durchsatz gemeinsam betrachten. Eine Maschine kann hydraulisch oder feststoffseitig limitieren.")}`;});
}
function renderCake(workspace){
  const fields=[techField(),numberField("tsLoad","TS-Fracht Zulauf","kg TS/d",0),numberField("retention","Feststoffrückhalt","%",0,100,95),numberField("cakeTs","TS im Schlammkuchen","%",0.000001,100,25),numberField("days","Betriebstage","d/a",0,366,365)];
  setup(workspace,formShell({category:"Schlammentwässerung",title:"Schlammkuchenmenge",formula:"mKuchen = mTS × η ÷ TS_Kuchen",description:"Berücksichtigt neben der TS-Fracht auch den Feststoffrückhalt der Maschine.",fields,info:'<div id="techInfo"></div>'}),()=>renderCake(workspace));
  bind(workspace,fields,(v,out)=>{const captured=v.tsLoad*v.retention/100,cake=captured/(v.cakeTs/100),water=cake-captured,lost=v.tsLoad-captured,annual=cake*v.days/1000;out.innerHTML=`<span class="tech-badge">${v.technique}</span><section class="result-hero"><small>Schlammkuchen</small><strong>${number(cake/1000,3)} t/d</strong><p>${number(v.cakeTs,2)} % TS · ${number(annual,1)} t/a</p></section><div class="metrics">${metric("Abgeschiedene TS",number(captured,2)+" kg/d")}${metric("Feststoffverlust",number(lost,2)+" kg TS/d")}${metric("Wasser im Kuchen",number(water/1000,3)+" t/d")}${metric("Schlammkuchen pro Jahr",number(annual,1)+" t/a")}</div>${hint("Massenbilanz",`Die Kuchenmenge basiert auf ${number(v.retention,2)} % Feststoffrückhalt. Ein niedriger Rückhalt reduziert rechnerisch die Kuchenmenge, erhöht aber die Rückbelastung über ${TECHNIQUES[v.technique].liquid}.`)}`;});
}
function renderRetention(workspace){
  const fields=[techField(),numberField("feedFlow","Zulaufstrom","m³/h",0.000001),numberField("feedTs","TS Zulauf","kg/m³",0),numberField("liquidFlow","Flüssigphasenstrom","m³/h",0),numberField("liquidTs","TS Flüssigphase","kg/m³",0)];
  setup(workspace,formShell({category:"Schlammentwässerung",title:"Feststoffrückhalt",formula:"η = (Bzu − Bab) ÷ Bzu × 100",description:"Vergleicht TS-Frachten statt nur Konzentrationen und benennt die Flüssigphase passend zur Technik.",fields,info:'<div id="techInfo"></div>'}),()=>renderRetention(workspace));
  bind(workspace,fields,(v,out)=>{const feed=v.feedFlow*v.feedTs,loss=v.liquidFlow*v.liquidTs,ret=(feed-loss)/feed*100;const kind=ret<0||ret>100?"danger":ret<90?"warning":"ok";out.innerHTML=`<span class="tech-badge">${v.technique}</span><section class="result-hero"><small>Feststoffrückhalt</small><strong>${number(ret,2)} %</strong><p>${number(feed,2)} kg TS/h Zulauf · ${number(loss,2)} kg TS/h im ${TECHNIQUES[v.technique].liquid}</p></section><div class="metrics">${metric("TS-Fracht Zulauf",number(feed,3)+" kg/h")}${metric(`TS-Fracht ${TECHNIQUES[v.technique].liquid}`,number(loss,3)+" kg/h")}${metric("Abgeschiedene TS",number(feed-loss,3)+" kg/h")}${metric("Feststoffverlust",number(feed?loss/feed*100:0,2)+" %")}</div>${hint("Plausibilität",ret<0||ret>100?"Die Massenbilanz liegt außerhalb 0–100 %. Volumenströme, Probenahmezeitpunkte und TS-Einheiten prüfen.":ret<90?"Der Feststoffrückhalt ist relativ niedrig. Flockung, Polymer, Maschinenparameter und Probenahme prüfen.":"Der berechnete Rückhalt liegt in einem plausiblen hohen Bereich; anlagenbezogene Zielwerte beachten.",kind)}`;});
}
function renderPolymer(workspace){
  const fields=[techField(),numberField("tsHour","TS-Durchsatz","kg TS/h",0),numberField("dose","Polymerdosierung","kg WS/t TS",0),selectField("productType","Produktart",["Pulverpolymer","Emulsionspolymer","Flüssigpolymer","Benutzerdefiniert"]),numberField("active","Wirksubstanzgehalt","%",0.000001,100,100),numberField("density","Produktdichte","kg/l",0.000001,Infinity,1),numberField("hours","Betriebszeit","h/d",0.000001,24,8),numberField("days","Betriebstage","d/a",0,366,250),numberField("price","Produktpreis","€/kg",0)];
  setup(workspace,formShell({category:"Schlammentwässerung",title:"Polymerbedarf",formula:"mWS = TS × Dosierung ÷ 1.000",description:"Berechnet Wirksubstanz und reale Produktmenge für Pulver-, Emulsions- oder Flüssigpolymer.",fields,info:'<div id="techInfo"></div>'}),()=>renderPolymer(workspace));
  bind(workspace,fields,(v,out)=>{const activeH=v.tsHour*v.dose/1000,productKgH=activeH/(v.active/100),productLH=productKgH/v.density,kgD=productKgH*v.hours,annual=kgD*v.days,costH=productKgH*v.price,costA=annual*v.price;out.innerHTML=`<span class="tech-badge">${v.technique} · ${v.productType}</span><section class="result-hero"><small>Polymerprodukt</small><strong>${number(productKgH,3)} kg/h</strong><p>${number(productLH,3)} l/h · ${number(kgD,2)} kg/d</p></section><div class="metrics">${metric("Wirksubstanz",number(activeH,3)+" kg WS/h")}${metric("Produktvolumen",number(productLH,3)+" l/h")}${metric("Produkt pro Jahr",number(annual/1000,2)+" t/a")}${metric("Kosten je t TS",money(v.dose/1000/(v.active/100)*v.price*1000))}${metric("Kosten pro Stunde",money(costH))}${metric("Kosten pro Jahr",money(costA))}</div>${hint("Dosierungsbasis",`Die Dosierung bezieht sich auf kg Polymer-Wirksubstanz je t TS. Bei handelsüblicher Angabe als kg Produkt/t TS den Wirksubstanzgehalt auf 100 % setzen oder die Eingabebasis entsprechend prüfen.`)}`;});
}
function renderDisposal(workspace){
  const fields=[techField(),numberField("cakeDay","Schlammkuchen","t/d",0),numberField("days","Entsorgungstage","d/a",0,366,250),numberField("disposalPrice","Entsorgungspreis","€/t",0),numberField("transportPrice","Transportkosten","€/t",0),numberField("fixed","Fixkosten","€/a",0)];
  setup(workspace,formShell({category:"Schlammentwässerung",title:"Entsorgungskosten",formula:"K = Menge × (Entsorgung + Transport) + Fixkosten",description:"Ermittelt Jahresmenge und Vollkosten der Schlammkuchenentsorgung.",fields,info:'<div id="techInfo"></div>'}),()=>renderDisposal(workspace));
  bind(workspace,fields,(v,out)=>{const annual=v.cakeDay*v.days,variable=annual*(v.disposalPrice+v.transportPrice),total=variable+v.fixed;out.innerHTML=`<span class="tech-badge">${v.technique}</span><section class="result-hero"><small>Gesamtkosten</small><strong>${money(total)}</strong><p>${number(annual,1)} t Schlammkuchen pro Jahr</p></section><div class="metrics">${metric("Entsorgung",money(annual*v.disposalPrice))}${metric("Transport",money(annual*v.transportPrice))}${metric("Fixkosten",money(v.fixed))}${metric("Kosten pro Tonne",annual?money(total/annual):money(0))}${metric("Kosten pro Betriebstag",v.days?money(total/v.days):money(0))}${metric("Jahresmenge",number(annual,1)+" t/a")}</div>`;});
}
function renderCompare(workspace){
  const common=[techField(),numberField("tsAnnual","Jährliche TS-Fracht","t TS/a",0),numberField("retention","Feststoffrückhalt","%",0,100,95),numberField("disposal","Entsorgung inkl. Transport","€/t Kuchen",0),numberField("polyActive","Polymer-Wirksubstanz","%",0.000001,100,100),numberField("polyPrice","Polymerpreis","€/kg Produkt",0)];
  const before=[numberField("cakeBefore","Kuchen-TS vorher","%",0.000001,100,22),numberField("doseBefore","Polymer vorher","kg WS/t TS",0)];
  const after=[numberField("cakeAfter","Kuchen-TS nachher","%",0.000001,100,27),numberField("doseAfter","Polymer nachher","kg WS/t TS",0)];
  const fields=[...common,...before,...after];
  setup(workspace,`<p class="eyebrow">Schlammentwässerung</p><h2>Vorher-Nachher-Vergleich</h2><span class="formula">Nettoeinsparung = Kosten vorher − Kosten nachher</span><p class="description">Vergleicht die Auswirkungen von Kuchen-TS und Polymerdosierung auf Schlammmenge und Jahreskosten.</p><form id="calculatorForm"><p class="section-title">Rahmendaten</p><div class="fields">${common.map(fieldHtml).join("")}</div><div id="techInfo" class="info-box"></div><p class="section-title">Vorher</p><div class="fields">${before.map(fieldHtml).join("")}</div><p class="section-title">Nachher</p><div class="fields">${after.map(fieldHtml).join("")}</div><div class="form-actions"><button class="button primary">Vergleichen</button><button type="button" id="resetForm" class="button secondary">Zurücksetzen</button></div></form><div id="result"></div>`,()=>renderCompare(workspace));
  bind(workspace,fields,(v,out)=>{const captured=v.tsAnnual*v.retention/100,cakeB=captured/(v.cakeBefore/100),cakeA=captured/(v.cakeAfter/100),disB=cakeB*v.disposal,disA=cakeA*v.disposal,polyKgB=v.tsAnnual*1000*v.doseBefore/1000/(v.polyActive/100),polyKgA=v.tsAnnual*1000*v.doseAfter/1000/(v.polyActive/100),polyCostB=polyKgB*v.polyPrice,polyCostA=polyKgA*v.polyPrice,totalB=disB+polyCostB,totalA=disA+polyCostA,saving=totalB-totalA;out.innerHTML=`<span class="tech-badge">${v.technique}</span><section class="result-hero"><small>Nettoveränderung pro Jahr</small><strong>${money(saving)}</strong><p>${saving>=0?"Einsparung":"Mehrkosten"} · ${number(cakeB-cakeA,1)} t/a weniger Schlammkuchen</p></section><div class="metrics">${metric("Kuchen vorher",number(cakeB,1)+" t/a")}${metric("Kuchen nachher",number(cakeA,1)+" t/a")}${metric("Entsorgung vorher",money(disB))}${metric("Entsorgung nachher",money(disA))}${metric("Polymer vorher",money(polyCostB))}${metric("Polymer nachher",money(polyCostA))}${metric("Gesamtkosten vorher",money(totalB))}${metric("Gesamtkosten nachher",money(totalA))}</div>${hint("Interpretation",`Der Vergleich hält TS-Jahresfracht und Feststoffrückhalt konstant. Änderungen bei Energie, Personal, Wartung, Wasser oder Investitionen sind noch nicht enthalten.`,saving>=0?"ok":"warning")}`;});
}
